services:
  hugot:
    image: hugot:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    # This service is build-only and not started
    entrypoint: ["/bin/true"]

  hugot-test:
    platform: linux/amd64
    container_name: hugot-test
    build:
      context: .
      dockerfile: ./test.Dockerfile
      target: hugot-test
    depends_on:
      - hugot
    volumes:
      - $test_folder:/test
      - $test_folder/../scripts/run-unit-tests-container.sh:/run-unit-tests-container.sh
    environment:
      - HOST_UID=$host_uid
      - CI=$CI
    command: /run-unit-tests-container.sh
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
